// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: img.proto

package com.siams.ml.images.api.proto;

public final class IMG {
  private IMG() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.siams.ml.images.api.proto.Tile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 dim_x = 1;</code>
     */
    boolean hasDimX();
    /**
     * <code>required uint32 dim_x = 1;</code>
     */
    int getDimX();

    /**
     * <code>required uint32 dim_y = 2;</code>
     */
    boolean hasDimY();
    /**
     * <code>required uint32 dim_y = 2;</code>
     */
    int getDimY();

    /**
     * <code>optional bytes r_g_b = 3;</code>
     */
    boolean hasRGB();
    /**
     * <code>optional bytes r_g_b = 3;</code>
     */
    com.google.protobuf.ByteString getRGB();

    /**
     * <code>optional bytes b_g_r = 4;</code>
     */
    boolean hasBGR();
    /**
     * <code>optional bytes b_g_r = 4;</code>
     */
    com.google.protobuf.ByteString getBGR();

    /**
     * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
     */
    boolean hasRegion();
    /**
     * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
     */
    com.siams.ml.images.api.proto.IMG.Tile.Region getRegion();
    /**
     * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
     */
    com.siams.ml.images.api.proto.IMG.Tile.RegionOrBuilder getRegionOrBuilder();
  }
  /**
   * Protobuf type {@code com.siams.ml.images.api.proto.Tile}
   */
  public static final class Tile extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.siams.ml.images.api.proto.Tile)
      TileOrBuilder {
    // Use Tile.newBuilder() to construct.
    private Tile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Tile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Tile defaultInstance;
    public static Tile getDefaultInstance() {
      return defaultInstance;
    }

    public Tile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Tile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dimX_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dimY_ = input.readUInt32();
              break;
            }
            case 26: {
              bytesCase_ = 3;
              bytes_ = input.readBytes();
              break;
            }
            case 34: {
              bytesCase_ = 4;
              bytes_ = input.readBytes();
              break;
            }
            case 82: {
              com.siams.ml.images.api.proto.IMG.Tile.Region.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = region_.toBuilder();
              }
              region_ = input.readMessage(com.siams.ml.images.api.proto.IMG.Tile.Region.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(region_);
                region_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.siams.ml.images.api.proto.IMG.Tile.class, com.siams.ml.images.api.proto.IMG.Tile.Builder.class);
    }

    public static com.google.protobuf.Parser<Tile> PARSER =
        new com.google.protobuf.AbstractParser<Tile>() {
      public Tile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Tile> getParserForType() {
      return PARSER;
    }

    public interface RegionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.siams.ml.images.api.proto.Tile.Region)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int64 from_x = 1;</code>
       */
      boolean hasFromX();
      /**
       * <code>required int64 from_x = 1;</code>
       */
      long getFromX();

      /**
       * <code>required int64 from_y = 2;</code>
       */
      boolean hasFromY();
      /**
       * <code>required int64 from_y = 2;</code>
       */
      long getFromY();

      /**
       * <code>required int64 to_x = 3;</code>
       */
      boolean hasToX();
      /**
       * <code>required int64 to_x = 3;</code>
       */
      long getToX();

      /**
       * <code>required int64 to_y = 4;</code>
       */
      boolean hasToY();
      /**
       * <code>required int64 to_y = 4;</code>
       */
      long getToY();

      /**
       * <code>optional double compression = 5;</code>
       */
      boolean hasCompression();
      /**
       * <code>optional double compression = 5;</code>
       */
      double getCompression();
    }
    /**
     * Protobuf type {@code com.siams.ml.images.api.proto.Tile.Region}
     */
    public static final class Region extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.siams.ml.images.api.proto.Tile.Region)
        RegionOrBuilder {
      // Use Region.newBuilder() to construct.
      private Region(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Region(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Region defaultInstance;
      public static Region getDefaultInstance() {
        return defaultInstance;
      }

      public Region getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Region(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                fromX_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                fromY_ = input.readInt64();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                toX_ = input.readInt64();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                toY_ = input.readInt64();
                break;
              }
              case 41: {
                bitField0_ |= 0x00000010;
                compression_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_Region_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_Region_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.siams.ml.images.api.proto.IMG.Tile.Region.class, com.siams.ml.images.api.proto.IMG.Tile.Region.Builder.class);
      }

      public static com.google.protobuf.Parser<Region> PARSER =
          new com.google.protobuf.AbstractParser<Region>() {
        public Region parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Region(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Region> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int FROM_X_FIELD_NUMBER = 1;
      private long fromX_;
      /**
       * <code>required int64 from_x = 1;</code>
       */
      public boolean hasFromX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 from_x = 1;</code>
       */
      public long getFromX() {
        return fromX_;
      }

      public static final int FROM_Y_FIELD_NUMBER = 2;
      private long fromY_;
      /**
       * <code>required int64 from_y = 2;</code>
       */
      public boolean hasFromY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 from_y = 2;</code>
       */
      public long getFromY() {
        return fromY_;
      }

      public static final int TO_X_FIELD_NUMBER = 3;
      private long toX_;
      /**
       * <code>required int64 to_x = 3;</code>
       */
      public boolean hasToX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 to_x = 3;</code>
       */
      public long getToX() {
        return toX_;
      }

      public static final int TO_Y_FIELD_NUMBER = 4;
      private long toY_;
      /**
       * <code>required int64 to_y = 4;</code>
       */
      public boolean hasToY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 to_y = 4;</code>
       */
      public long getToY() {
        return toY_;
      }

      public static final int COMPRESSION_FIELD_NUMBER = 5;
      private double compression_;
      /**
       * <code>optional double compression = 5;</code>
       */
      public boolean hasCompression() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double compression = 5;</code>
       */
      public double getCompression() {
        return compression_;
      }

      private void initFields() {
        fromX_ = 0L;
        fromY_ = 0L;
        toX_ = 0L;
        toY_ = 0L;
        compression_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasFromX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFromY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasToX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasToY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, fromX_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, fromY_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(3, toX_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt64(4, toY_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeDouble(5, compression_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, fromX_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, fromY_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, toX_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(4, toY_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(5, compression_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.siams.ml.images.api.proto.IMG.Tile.Region parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.siams.ml.images.api.proto.IMG.Tile.Region prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.siams.ml.images.api.proto.Tile.Region}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.siams.ml.images.api.proto.Tile.Region)
          com.siams.ml.images.api.proto.IMG.Tile.RegionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_Region_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_Region_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.siams.ml.images.api.proto.IMG.Tile.Region.class, com.siams.ml.images.api.proto.IMG.Tile.Region.Builder.class);
        }

        // Construct using com.siams.ml.images.api.proto.IMG.Tile.Region.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          fromX_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          fromY_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          toX_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          toY_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000008);
          compression_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_Region_descriptor;
        }

        public com.siams.ml.images.api.proto.IMG.Tile.Region getDefaultInstanceForType() {
          return com.siams.ml.images.api.proto.IMG.Tile.Region.getDefaultInstance();
        }

        public com.siams.ml.images.api.proto.IMG.Tile.Region build() {
          com.siams.ml.images.api.proto.IMG.Tile.Region result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.siams.ml.images.api.proto.IMG.Tile.Region buildPartial() {
          com.siams.ml.images.api.proto.IMG.Tile.Region result = new com.siams.ml.images.api.proto.IMG.Tile.Region(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.fromX_ = fromX_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.fromY_ = fromY_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.toX_ = toX_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.toY_ = toY_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.compression_ = compression_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.siams.ml.images.api.proto.IMG.Tile.Region) {
            return mergeFrom((com.siams.ml.images.api.proto.IMG.Tile.Region)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.siams.ml.images.api.proto.IMG.Tile.Region other) {
          if (other == com.siams.ml.images.api.proto.IMG.Tile.Region.getDefaultInstance()) return this;
          if (other.hasFromX()) {
            setFromX(other.getFromX());
          }
          if (other.hasFromY()) {
            setFromY(other.getFromY());
          }
          if (other.hasToX()) {
            setToX(other.getToX());
          }
          if (other.hasToY()) {
            setToY(other.getToY());
          }
          if (other.hasCompression()) {
            setCompression(other.getCompression());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasFromX()) {
            
            return false;
          }
          if (!hasFromY()) {
            
            return false;
          }
          if (!hasToX()) {
            
            return false;
          }
          if (!hasToY()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.siams.ml.images.api.proto.IMG.Tile.Region parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.siams.ml.images.api.proto.IMG.Tile.Region) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long fromX_ ;
        /**
         * <code>required int64 from_x = 1;</code>
         */
        public boolean hasFromX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 from_x = 1;</code>
         */
        public long getFromX() {
          return fromX_;
        }
        /**
         * <code>required int64 from_x = 1;</code>
         */
        public Builder setFromX(long value) {
          bitField0_ |= 0x00000001;
          fromX_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 from_x = 1;</code>
         */
        public Builder clearFromX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          fromX_ = 0L;
          onChanged();
          return this;
        }

        private long fromY_ ;
        /**
         * <code>required int64 from_y = 2;</code>
         */
        public boolean hasFromY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 from_y = 2;</code>
         */
        public long getFromY() {
          return fromY_;
        }
        /**
         * <code>required int64 from_y = 2;</code>
         */
        public Builder setFromY(long value) {
          bitField0_ |= 0x00000002;
          fromY_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 from_y = 2;</code>
         */
        public Builder clearFromY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          fromY_ = 0L;
          onChanged();
          return this;
        }

        private long toX_ ;
        /**
         * <code>required int64 to_x = 3;</code>
         */
        public boolean hasToX() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required int64 to_x = 3;</code>
         */
        public long getToX() {
          return toX_;
        }
        /**
         * <code>required int64 to_x = 3;</code>
         */
        public Builder setToX(long value) {
          bitField0_ |= 0x00000004;
          toX_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 to_x = 3;</code>
         */
        public Builder clearToX() {
          bitField0_ = (bitField0_ & ~0x00000004);
          toX_ = 0L;
          onChanged();
          return this;
        }

        private long toY_ ;
        /**
         * <code>required int64 to_y = 4;</code>
         */
        public boolean hasToY() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required int64 to_y = 4;</code>
         */
        public long getToY() {
          return toY_;
        }
        /**
         * <code>required int64 to_y = 4;</code>
         */
        public Builder setToY(long value) {
          bitField0_ |= 0x00000008;
          toY_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 to_y = 4;</code>
         */
        public Builder clearToY() {
          bitField0_ = (bitField0_ & ~0x00000008);
          toY_ = 0L;
          onChanged();
          return this;
        }

        private double compression_ ;
        /**
         * <code>optional double compression = 5;</code>
         */
        public boolean hasCompression() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional double compression = 5;</code>
         */
        public double getCompression() {
          return compression_;
        }
        /**
         * <code>optional double compression = 5;</code>
         */
        public Builder setCompression(double value) {
          bitField0_ |= 0x00000010;
          compression_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double compression = 5;</code>
         */
        public Builder clearCompression() {
          bitField0_ = (bitField0_ & ~0x00000010);
          compression_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.siams.ml.images.api.proto.Tile.Region)
      }

      static {
        defaultInstance = new Region(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.siams.ml.images.api.proto.Tile.Region)
    }

    private int bitField0_;
    private int bytesCase_ = 0;
    private java.lang.Object bytes_;
    public enum BytesCase
        implements com.google.protobuf.Internal.EnumLite {
      R_G_B(3),
      B_G_R(4),
      BYTES_NOT_SET(0);
      private int value = 0;
      private BytesCase(int value) {
        this.value = value;
      }
      public static BytesCase valueOf(int value) {
        switch (value) {
          case 3: return R_G_B;
          case 4: return B_G_R;
          case 0: return BYTES_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BytesCase
    getBytesCase() {
      return BytesCase.valueOf(
          bytesCase_);
    }

    public static final int DIM_X_FIELD_NUMBER = 1;
    private int dimX_;
    /**
     * <code>required uint32 dim_x = 1;</code>
     */
    public boolean hasDimX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 dim_x = 1;</code>
     */
    public int getDimX() {
      return dimX_;
    }

    public static final int DIM_Y_FIELD_NUMBER = 2;
    private int dimY_;
    /**
     * <code>required uint32 dim_y = 2;</code>
     */
    public boolean hasDimY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 dim_y = 2;</code>
     */
    public int getDimY() {
      return dimY_;
    }

    public static final int R_G_B_FIELD_NUMBER = 3;
    /**
     * <code>optional bytes r_g_b = 3;</code>
     */
    public boolean hasRGB() {
      return bytesCase_ == 3;
    }
    /**
     * <code>optional bytes r_g_b = 3;</code>
     */
    public com.google.protobuf.ByteString getRGB() {
      if (bytesCase_ == 3) {
        return (com.google.protobuf.ByteString) bytes_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int B_G_R_FIELD_NUMBER = 4;
    /**
     * <code>optional bytes b_g_r = 4;</code>
     */
    public boolean hasBGR() {
      return bytesCase_ == 4;
    }
    /**
     * <code>optional bytes b_g_r = 4;</code>
     */
    public com.google.protobuf.ByteString getBGR() {
      if (bytesCase_ == 4) {
        return (com.google.protobuf.ByteString) bytes_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int REGION_FIELD_NUMBER = 10;
    private com.siams.ml.images.api.proto.IMG.Tile.Region region_;
    /**
     * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
     */
    public com.siams.ml.images.api.proto.IMG.Tile.Region getRegion() {
      return region_;
    }
    /**
     * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
     */
    public com.siams.ml.images.api.proto.IMG.Tile.RegionOrBuilder getRegionOrBuilder() {
      return region_;
    }

    private void initFields() {
      dimX_ = 0;
      dimY_ = 0;
      region_ = com.siams.ml.images.api.proto.IMG.Tile.Region.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDimX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDimY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasRegion()) {
        if (!getRegion().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, dimX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, dimY_);
      }
      if (bytesCase_ == 3) {
        output.writeBytes(
            3, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) bytes_));
      }
      if (bytesCase_ == 4) {
        output.writeBytes(
            4, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) bytes_));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(10, region_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, dimX_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, dimY_);
      }
      if (bytesCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              3, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) bytes_));
      }
      if (bytesCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              4, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) bytes_));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, region_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.siams.ml.images.api.proto.IMG.Tile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.siams.ml.images.api.proto.IMG.Tile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.siams.ml.images.api.proto.Tile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.siams.ml.images.api.proto.Tile)
        com.siams.ml.images.api.proto.IMG.TileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.siams.ml.images.api.proto.IMG.Tile.class, com.siams.ml.images.api.proto.IMG.Tile.Builder.class);
      }

      // Construct using com.siams.ml.images.api.proto.IMG.Tile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRegionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dimX_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dimY_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (regionBuilder_ == null) {
          region_ = com.siams.ml.images.api.proto.IMG.Tile.Region.getDefaultInstance();
        } else {
          regionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        bytesCase_ = 0;
        bytes_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.siams.ml.images.api.proto.IMG.internal_static_com_siams_ml_images_api_proto_Tile_descriptor;
      }

      public com.siams.ml.images.api.proto.IMG.Tile getDefaultInstanceForType() {
        return com.siams.ml.images.api.proto.IMG.Tile.getDefaultInstance();
      }

      public com.siams.ml.images.api.proto.IMG.Tile build() {
        com.siams.ml.images.api.proto.IMG.Tile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.siams.ml.images.api.proto.IMG.Tile buildPartial() {
        com.siams.ml.images.api.proto.IMG.Tile result = new com.siams.ml.images.api.proto.IMG.Tile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dimX_ = dimX_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dimY_ = dimY_;
        if (bytesCase_ == 3) {
          result.bytes_ = bytes_;
        }
        if (bytesCase_ == 4) {
          result.bytes_ = bytes_;
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (regionBuilder_ == null) {
          result.region_ = region_;
        } else {
          result.region_ = regionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        result.bytesCase_ = bytesCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.siams.ml.images.api.proto.IMG.Tile) {
          return mergeFrom((com.siams.ml.images.api.proto.IMG.Tile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.siams.ml.images.api.proto.IMG.Tile other) {
        if (other == com.siams.ml.images.api.proto.IMG.Tile.getDefaultInstance()) return this;
        if (other.hasDimX()) {
          setDimX(other.getDimX());
        }
        if (other.hasDimY()) {
          setDimY(other.getDimY());
        }
        if (other.hasRegion()) {
          mergeRegion(other.getRegion());
        }
        switch (other.getBytesCase()) {
          case R_G_B: {
            setRGB(other.getRGB());
            break;
          }
          case B_G_R: {
            setBGR(other.getBGR());
            break;
          }
          case BYTES_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDimX()) {
          
          return false;
        }
        if (!hasDimY()) {
          
          return false;
        }
        if (hasRegion()) {
          if (!getRegion().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.siams.ml.images.api.proto.IMG.Tile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.siams.ml.images.api.proto.IMG.Tile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bytesCase_ = 0;
      private java.lang.Object bytes_;
      public BytesCase
          getBytesCase() {
        return BytesCase.valueOf(
            bytesCase_);
      }

      public Builder clearBytes() {
        bytesCase_ = 0;
        bytes_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dimX_ ;
      /**
       * <code>required uint32 dim_x = 1;</code>
       */
      public boolean hasDimX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 dim_x = 1;</code>
       */
      public int getDimX() {
        return dimX_;
      }
      /**
       * <code>required uint32 dim_x = 1;</code>
       */
      public Builder setDimX(int value) {
        bitField0_ |= 0x00000001;
        dimX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 dim_x = 1;</code>
       */
      public Builder clearDimX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dimX_ = 0;
        onChanged();
        return this;
      }

      private int dimY_ ;
      /**
       * <code>required uint32 dim_y = 2;</code>
       */
      public boolean hasDimY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 dim_y = 2;</code>
       */
      public int getDimY() {
        return dimY_;
      }
      /**
       * <code>required uint32 dim_y = 2;</code>
       */
      public Builder setDimY(int value) {
        bitField0_ |= 0x00000002;
        dimY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 dim_y = 2;</code>
       */
      public Builder clearDimY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dimY_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>optional bytes r_g_b = 3;</code>
       */
      public boolean hasRGB() {
        return bytesCase_ == 3;
      }
      /**
       * <code>optional bytes r_g_b = 3;</code>
       */
      public com.google.protobuf.ByteString getRGB() {
        if (bytesCase_ == 3) {
          return (com.google.protobuf.ByteString) bytes_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>optional bytes r_g_b = 3;</code>
       */
      public Builder setRGB(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bytesCase_ = 3;
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes r_g_b = 3;</code>
       */
      public Builder clearRGB() {
        if (bytesCase_ == 3) {
          bytesCase_ = 0;
          bytes_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bytes b_g_r = 4;</code>
       */
      public boolean hasBGR() {
        return bytesCase_ == 4;
      }
      /**
       * <code>optional bytes b_g_r = 4;</code>
       */
      public com.google.protobuf.ByteString getBGR() {
        if (bytesCase_ == 4) {
          return (com.google.protobuf.ByteString) bytes_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>optional bytes b_g_r = 4;</code>
       */
      public Builder setBGR(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bytesCase_ = 4;
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes b_g_r = 4;</code>
       */
      public Builder clearBGR() {
        if (bytesCase_ == 4) {
          bytesCase_ = 0;
          bytes_ = null;
          onChanged();
        }
        return this;
      }

      private com.siams.ml.images.api.proto.IMG.Tile.Region region_ = com.siams.ml.images.api.proto.IMG.Tile.Region.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.siams.ml.images.api.proto.IMG.Tile.Region, com.siams.ml.images.api.proto.IMG.Tile.Region.Builder, com.siams.ml.images.api.proto.IMG.Tile.RegionOrBuilder> regionBuilder_;
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public boolean hasRegion() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public com.siams.ml.images.api.proto.IMG.Tile.Region getRegion() {
        if (regionBuilder_ == null) {
          return region_;
        } else {
          return regionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public Builder setRegion(com.siams.ml.images.api.proto.IMG.Tile.Region value) {
        if (regionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          region_ = value;
          onChanged();
        } else {
          regionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public Builder setRegion(
          com.siams.ml.images.api.proto.IMG.Tile.Region.Builder builderForValue) {
        if (regionBuilder_ == null) {
          region_ = builderForValue.build();
          onChanged();
        } else {
          regionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public Builder mergeRegion(com.siams.ml.images.api.proto.IMG.Tile.Region value) {
        if (regionBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              region_ != com.siams.ml.images.api.proto.IMG.Tile.Region.getDefaultInstance()) {
            region_ =
              com.siams.ml.images.api.proto.IMG.Tile.Region.newBuilder(region_).mergeFrom(value).buildPartial();
          } else {
            region_ = value;
          }
          onChanged();
        } else {
          regionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public Builder clearRegion() {
        if (regionBuilder_ == null) {
          region_ = com.siams.ml.images.api.proto.IMG.Tile.Region.getDefaultInstance();
          onChanged();
        } else {
          regionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public com.siams.ml.images.api.proto.IMG.Tile.Region.Builder getRegionBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getRegionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      public com.siams.ml.images.api.proto.IMG.Tile.RegionOrBuilder getRegionOrBuilder() {
        if (regionBuilder_ != null) {
          return regionBuilder_.getMessageOrBuilder();
        } else {
          return region_;
        }
      }
      /**
       * <code>optional .com.siams.ml.images.api.proto.Tile.Region region = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.siams.ml.images.api.proto.IMG.Tile.Region, com.siams.ml.images.api.proto.IMG.Tile.Region.Builder, com.siams.ml.images.api.proto.IMG.Tile.RegionOrBuilder> 
          getRegionFieldBuilder() {
        if (regionBuilder_ == null) {
          regionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.siams.ml.images.api.proto.IMG.Tile.Region, com.siams.ml.images.api.proto.IMG.Tile.Region.Builder, com.siams.ml.images.api.proto.IMG.Tile.RegionOrBuilder>(
                  getRegion(),
                  getParentForChildren(),
                  isClean());
          region_ = null;
        }
        return regionBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.siams.ml.images.api.proto.Tile)
    }

    static {
      defaultInstance = new Tile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.siams.ml.images.api.proto.Tile)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_siams_ml_images_api_proto_Tile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_siams_ml_images_api_proto_Tile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_siams_ml_images_api_proto_Tile_Region_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_siams_ml_images_api_proto_Tile_Region_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\timg.proto\022\035com.siams.ml.images.api.pro" +
      "to\"\346\001\n\004Tile\022\r\n\005dim_x\030\001 \002(\r\022\r\n\005dim_y\030\002 \002(" +
      "\r\022\017\n\005r_g_b\030\003 \001(\014H\000\022\017\n\005b_g_r\030\004 \001(\014H\000\022:\n\006r" +
      "egion\030\n \001(\0132*.com.siams.ml.images.api.pr" +
      "oto.Tile.Region\032Y\n\006Region\022\016\n\006from_x\030\001 \002(" +
      "\003\022\016\n\006from_y\030\002 \002(\003\022\014\n\004to_x\030\003 \002(\003\022\014\n\004to_y\030" +
      "\004 \002(\003\022\023\n\013compression\030\005 \001(\001B\007\n\005bytesB\007B\003I" +
      "MGH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_siams_ml_images_api_proto_Tile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_siams_ml_images_api_proto_Tile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_siams_ml_images_api_proto_Tile_descriptor,
        new java.lang.String[] { "DimX", "DimY", "RGB", "BGR", "Region", "Bytes", });
    internal_static_com_siams_ml_images_api_proto_Tile_Region_descriptor =
      internal_static_com_siams_ml_images_api_proto_Tile_descriptor.getNestedTypes().get(0);
    internal_static_com_siams_ml_images_api_proto_Tile_Region_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_siams_ml_images_api_proto_Tile_Region_descriptor,
        new java.lang.String[] { "FromX", "FromY", "ToX", "ToY", "Compression", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
